# !! INTENTIONAL WEAKNESS: Granting cluster-admin to the default service account in wizapp namespace. 
# Granting the default service account cluster-admin access is very risky in production.
# It means any pod running in that namespace can now control the entire cluster
# This is a simplified way to achieve the "container with cluster-admin privileges" requirement.
# A more targeted approach would be to create a specific ServiceAccount for your deployment
# and bind that ServiceAccount to the cluster-admin ClusterRole.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wizapp-default-cluster-admin # Name of this binding
subjects:
- kind: ServiceAccount
  name: default # Apply to the 'default' service account
  namespace: wizapp # In your application's namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin # The built-in cluster-admin role
  apiGroup: rbac.authorization.k8s.io
