apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizapp-deployment
  namespace: wizapp
  labels:
    app: wizapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wizapp
  template:
    metadata:
      labels:
        app: wizapp
    spec:
      # !! INTENTIONAL WEAKNESS: Assign cluster-admin ServiceAccount (or default with ClusterRoleBinding) !!
      # serviceAccountName: wizapp-sa # If you create a specific SA
      containers:
      - name: wizapp-container
        # This will be dynamically replaced by the CI/CD pipeline.
        # Example of what it might look like after replacement:
        # image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/wizexercise-app-repo:abcdef1
        image: DYNAMICALLY_REPLACED_BY_CI_CD_PIPELINE # E.g., 123456789012.dkr.ecr.us-east-1.amazonaws.com/wizexercise-app-repo:commitsha
        ports:
        - containerPort: 3000 # Port your application listens on
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_URI
        # Add readiness and liveness probes for production-grade deployments
        readinessProbe:
          httpGet:
            path: / # Or an actual health check endpoint
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: / # Or an actual health check endpoint
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
