apiVersion: apps/v1
kind: Deployment  # Declares this resource is a Deployment (manages replicas of Pods).
metadata:
  name: wizapp-deployment
  namespace: wizapp   #Places the Deployment in the 'wizapp' namespace.
  labels:
    app: wizapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wizapp
  template:
    metadata:
      labels:
        app: wizapp
    spec:
      # !! INTENTIONAL WEAKNESS: Uses 'default' ServiceAccount which is bound to cluster-admin via ClusterRoleBinding !!
      # serviceAccountName: default 
      containers:
      - name: wizapp-container
        # This placeholder will be replaced by the CI/CD pipeline with the actual ECR image URI.
        # Example after replacement: image: [123456789012.dkr.ecr.us-east-1.amazonaws.com/wizexercise-app-repo:abcdef1](https://123456789012.dkr.ecr.us-east-1.amazonaws.com/wizexercise-app-repo:abcdef1)
        image: DYNAMICALLY_REPLACED_BY_CI_CD_PIPELINE # This exact string is targeted by sed in CI/CD
        ports:
        - containerPort: 3000 # Port your application listens on (must match app/Dockerfile EXPOSE and app/server.js port)
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_URI
        # Add readiness and liveness probes for production-grade deployments
        readinessProbe:
          httpGet:
            path: / # Your app's root or a specific health check endpoint
            port: 3000
          initialDelaySeconds: 20 # Give some time for the app to start
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: / # Your app's root or a specific health check endpoint
            port: 3000
          initialDelaySeconds: 45 # Longer delay for liveness
          periodSeconds: 20
          failureThreshold: 3
