apiVersion: v1
kind: Service
metadata:
  name: wizapp-service
  namespace: wizapp
  labels:
    app: wizapp
  annotations:
    # Optional: Use AWS Load Balancer Controller annotations for specific features if ALB/NLB controller is installed.
    # For a basic LoadBalancer service type, these are not strictly needed.
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # or "alb" (requires AWS Load Balancer Controller)
    # service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer # This will provision an AWS Classic Load Balancer by default, or NLB/ALB if controller is used.
  selector:
    app: wizapp # Must match labels in your Deployment's template
  ports:
  - protocol: TCP
    port: 80 # Port the Load Balancer listens on
    targetPort: 3000 # Port your container (application) listens on
