apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wizapp
type: Opaque # Opaque means this secret holds arbitrary key-value pairs (standard choice for generic secrets).
data:
  MONGODB_URI: bW9uZ29kYjovL3dpemFkbWluOmxha3NoaW1hJTQwMTIzQDEwLjAuMC4yMjY6MjcwMTcvdGFza3lkYj9hdXRoU291cmNlPWFkbWlu # This is the actual secret value, but it’s stored base64-encoded for safety.
  
  # Example (DO NOT USE THIS LITERALLY, IT'S A PLACEHOLDER):
  # MONGODB_URI: bW9uZ29kYjovL3dpemFkbWluOlBBU1NXT1JEQGFiYy5kZWYuZ2hpLmlqazoyNzAxNy90YXNreWRiP2F1dGhTb3VyY2U9YWRtaW4=
#echo -n 'mongodb://wizadmin:lakshima%40123@10.0.0.226:27017/taskydb?authSource=admin' | base64
