apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wizapp
type: Opaque
data:
  # The MONGODB_URI must be base64 encoded.
  # Example command to encode:
  # echo -n 'mongodb://wizadmin:YOUR_ACTUAL_DB_PASSWORD@YOUR_MONGODB_EC2_PUBLIC_IP:27017/taskydb?authSource=admin' | base64
  #
  # Replace the placeholder below with your actual base64 encoded string.
  # Ensure YOUR_ACTUAL_DB_PASSWORD and YOUR_MONGODB_EC2_PUBLIC_IP are correct.
  # The database name 'taskydb' is an example; use the DB your app connects to.
  # 'authSource=admin' means the user 'wizadmin' is defined in the 'admin' database.
  MONGODB_URI: bW9uZ29kYjovL3dpemFkbWluOmxha3NoaW1hJTQwMTIzQDEwLjAuMC4yMjY6MjcwMTcvdGFza3lkYj9hdXRoU291cmNlPWFkbWlu
  # Example (DO NOT USE THIS LITERALLY, IT'S A PLACEHOLDER):
  # MONGODB_URI: bW9uZ29kYjovL3dpemFkbWluOlBBU1NXT1JEQGFiYy5kZWYuZ2hpLmlqazoyNzAxNy90YXNreWRiP2F1dGhTb3VyY2U9YWRtaW4=
#echo -n 'mongodb://wizadmin:lakshima%40123@10.0.0.226:27017/taskydb?authSource=admin' | base64
